### ISSUE TITLE
Fails to deserialize from a plain array using Serializer

### ISSUE THREAD

**Issue by garkin** [weichx/cerialize#6]
Tests: https://github.com/garkin/cerialize/commit/2dd885a6641dc0f10cb8776ecfdc1986031f5ca2
```
Failures:
1) autoserializeAs using Serializer to plain array data will be deserialized
1.1) Expected false to be truthy.
    Error: Expected false to be truthy.
        at stack (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1577:17)
        at buildExpectationResult (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1547:14)
        at Spec.Env.expectationResultFactory (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:638:18)
        at Spec.addExpectationResult (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:330:34)
        at Expectation.addExpectationResult (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:588:21)
        at Expectation.toBeTruthy (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1501:12)
        at Object.<anonymous> (C:\WORKSHOP\_little_games\cerialize\cerialize\spec\spec\autoserialize_annotation_spec.js:184:52)
        at attemptSync (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1886:24)
        at QueueRunner.run (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1874:9)
        at QueueRunner.execute (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1859:10)

2) autoserializeAs using Serializer to plain array data will be deserializedInto
2.1) TypeError: object is not a function
    TypeError: object is not a function
        at deserializeArrayInto (C:\WORKSHOP\_little_games\cerialize\cerialize\spec\src\serialize.js:258:81)
        at deserializeObjectInto (C:\WORKSHOP\_little_games\cerialize\cerialize\spec\src\serialize.js:300:37)
        at Object.DeserializeInto (C:\WORKSHOP\_little_games\cerialize\cerialize\spec\src\serialize.js:340:16)
        at Object.<anonymous> (C:\WORKSHOP\_little_games\cerialize\cerialize\spec\spec\autoserialize_annotation_spec.js:188:38)
        at attemptSync (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1886:24)
        at QueueRunner.run (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1874:9)
        at QueueRunner.execute (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1859:10)
        at Spec.Env.queueRunnerFactory (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:697:35)
        at Spec.execute (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:359:10)
        at Object.fn (C:\WORKSHOP\_little_games\cerialize\cerialize\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2479:37)


70 specs, 2 failures
Finished in 0 seconds
```

**Comment by weichx** [comment]
thanks again for the contribution, huge help! https://github.com/weichx/cerialize/pull/7
