### ISSUE TITLE
Reflection & Hoisting 

### ISSUE THREAD

**Issue by rightisleft** [weichx/cerialize#74]
I'm debugging the following error. 

TypeError: decorator is not a function
    at DecorateProperty (/Users/jmurphy/projects/ubq/api/node_modules/reflect-metadata/Reflect.js:530:29)
    at Object.decorate (/Users/jmurphy/projects/ubq/api/node_modules/reflect-metadata/Reflect.js:100:20)
    at __decorate (/Users/jmurphy/projects/ubq/api/dist/src/ubq/dtos/lens.dto.js:4:92)
    at Object.<anonymous> (/Users/jmurphy/projects/ubq/api/dist/src/ubq/dtos/lens.dto.js:73:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

It occurs when using autoSerializeAs(Foo) 

Is there support for getting the class type by function as outlined here?

https://github.com/rbuckton/reflect-metadata/issues/29

The core issue comes from trying to implement this library:
https://github.com/typeorm/typeorm/issues/1060

**Comment by rightisleft** [comment]
I setup a simple test with 2 entities that use both Address and Owner. This is designed specifically to test fat arrow type assignment. 

1: Using an expression to

```
export class Address {
    @autoserialize name: string;
    @autoserialize unit: number;
    @autoserializeAs(() => Owner) owner: Owner
}

// Address { name: 'carl', unit: 2, owner: [Function: Owner] }
```

Using:

```
export class Address {
    @autoserialize name: string;
    @autoserialize unit: number;
    @autoserialize owner: Owner
}

// Address { name: 'carl', unit: 2, owner: { type: 'owner', name: 'bank' } }
```

**Comment by rightisleft** [comment]
From the other author:
https://github.com/typeorm/typeorm/issues/1060

**Comment by weichx** [comment]
This should be solved in version 2 https://github.com/weichx/cerialize/tree/mw/v2 using `@serializeUsing`
